services:
  - type: web
    name: django-todo-app
    env: python
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt && python manage.py collectstatic --noinput
    startCommand: python run_server.py
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: todo-nsz6.onrender.com
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: PORT
        value: "8000"

